[package]
name = "crckill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
byteorder = "1"
log = "0.4"
env_logger = "0.11"
num_enum = "0.7"
rand = "0.8"
